version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - dbvolume1:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example

volumes:
  dbvolume1: {}